version: "3.8"
services:
  server:
    image: alex_server
    networks:
      - net7
    ports:
    - target: 8080
      published: 8082
  client:
    image: alex_client
    networks:
      - net7
    ports:
    - target: 8080
      published: 8081
networks:
  net7:
